# permissions for end users to view tracingconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tracingconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trickster-config
    app.kubernetes.io/part-of: trickster-config
    app.kubernetes.io/managed-by: kustomize
  name: tracingconfig-viewer-role
rules:
- apiGroups:
  - trickstercache.org
  resources:
  - tracingconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trickstercache.org
  resources:
  - tracingconfigs/status
  verbs:
  - get
