# permissions for end users to edit trickstercaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trickstercache-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trickster-config
    app.kubernetes.io/part-of: trickster-config
    app.kubernetes.io/managed-by: kustomize
  name: trickstercache-editor-role
rules:
- apiGroups:
  - trickstercache.org
  resources:
  - trickstercaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trickstercache.org
  resources:
  - trickstercaches/status
  verbs:
  - get
