# permissions for end users to edit tricksters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trickster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trickster-config
    app.kubernetes.io/part-of: trickster-config
    app.kubernetes.io/managed-by: kustomize
  name: trickster-editor-role
rules:
- apiGroups:
  - trickstercache.org
  resources:
  - tricksters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trickstercache.org
  resources:
  - tricksters/status
  verbs:
  - get
