apiVersion: trickstercache.org/v1alpha1
kind: Backend
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend-sample
    app.kubernetes.io/part-of: trickster-config
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trickster-config
  name: backend-sample
spec:
  # TODO(user): Add fields here
