apiVersion: trickstercache.org/v1alpha1
kind: RequestRewriter
metadata:
  labels:
    app.kubernetes.io/name: requestrewriter
    app.kubernetes.io/instance: requestrewriter-sample
    app.kubernetes.io/part-of: trickster-config
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trickster-config
  name: requestrewriter-sample
spec:
  # TODO(user): Add fields here
