apiVersion: trickstercache.org/v1alpha1
kind: Rule
metadata:
  labels:
    app.kubernetes.io/name: rule
    app.kubernetes.io/instance: rule-sample
    app.kubernetes.io/part-of: trickster-config
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trickster-config
  name: rule-sample
spec:
  # TODO(user): Add fields here
